# Generated by Django 3.0.2 on 2020-01-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sathi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('available', models.BooleanField()),
                ('time', models.DateField()),
                ('duration', models.DurationField()),
                ('languages', models.CharField(max_length=50)),
                ('interests', models.CharField(max_length=250)),
                ('places', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images')),
                ('sathi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sathi')),
            ],
        ),
    ]
