# Generated by Django 3.0.2 on 2020-01-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=15, unique=True)),
                ('name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100)),
                ('posted_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
