# Generated by Django 3.0.2 on 2020-01-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodprovider',
            name='price',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='sathi',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
