# Generated by Django 3.0.2 on 2020-01-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sathi',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
