# Generated by Django 3.0.2 on 2020-01-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200110_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sathi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('available', models.BooleanField()),
                ('Afrom', models.DateField(auto_now_add=True)),
                ('to', models.DateField(auto_now_add=True)),
                ('languages', models.CharField(max_length=50)),
                ('interests', models.CharField(max_length=250)),
                ('places', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='resources/images')),
                ('sathi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sathi')),
            ],
        ),
    ]
