# Generated by Django 3.0.2 on 2020-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200121_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sathi',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
