# Generated by Django 3.0.2 on 2020-02-09 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200209_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodprovider',
            old_name='dishes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='eventimages',
            name='describe',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='image',
            field=models.ImageField(upload_to='eventimages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='eventtime',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 9, 18, 59, 39, 70337)),
        ),
        migrations.AlterField(
            model_name='foodtime',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 9, 18, 59, 39, 70337)),
        ),
        migrations.AlterField(
            model_name='sathitime',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 9, 18, 59, 39, 70337)),
        ),
    ]
