# Generated by Django 3.0.2 on 2020-01-24 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('docType', models.CharField(choices=[('passport', 'PASSPORT'), ('license', 'LICENSE'), ('citizen', 'CITIZENSHIP')], default='', max_length=10)),
                ('docID', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(default='Kathmandu', max_length=50)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 1, 24, 7, 32, 22, 291324))),
                ('host', models.CharField(max_length=50)),
                ('pricing', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='thumbnail/', verbose_name='Image')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('describe', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Event')),
            ],
        ),
    ]
