# Generated by Django 3.0.2 on 2020-01-24 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookingdata_event_eventimages_eventthumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 17, 29, 16, 962511)),
        ),
    ]
