# Generated by Django 3.0.2 on 2020-01-26 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200125_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RenameField(
            model_name='foodprovider',
            old_name='place',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='sathi',
            old_name='places',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 3, 54, 19, 978156)),
        ),
    ]
