# Generated by Django 3.0.2 on 2020-02-11 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200209_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 11, 15, 47, 41, 891935)),
        ),
        migrations.AlterField(
            model_name='foodtime',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 11, 15, 47, 41, 890572)),
        ),
        migrations.AlterField(
            model_name='sathitime',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 11, 15, 47, 41, 889463)),
        ),
    ]
