# Generated by Django 3.0.2 on 2020-02-05 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200205_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 21, 39, 37, 17942)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sathi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.Sathi'),
        ),
    ]
