# Generated by Django 3.0.2 on 2020-02-06 15:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20200205_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingdata', to='api.Event'),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingdata', to='api.FoodProvider'),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='sathi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingdata', to='api.Sathi'),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingdata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 20, 54, 51, 425955)),
        ),
    ]
