# Generated by Django 3.0.2 on 2020-02-07 02:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20200206_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docID', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='event',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='food',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='sathi',
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='categoryId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 5, 33, 804433)),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 5, 33, 803438)),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
